add: component Comite do Programa e populando membros
gesid/novo-washes-website pull request #6
Opened 2024-09-20 21:31 UTC by gustavo-reinaldo

2024-09-22 04:49 UTC, guilhermehub12 submitted a review, later dismissed
Código revisado e aprovado!

2024-09-22 04:51 UTC, guilhermehub12 requested changes
Código revisado. 

Faltou colocar as imagens dos membros e coordenadores, além dos ícones das redes sociais.

2024-09-23 23:51 UTC, gustavo-reinaldo commented
@guilhermehub12  Será colocado as fotos pelo Otavio, passei pra ele como uma primeira atividade pra se habituar com o código.

2024-09-24 00:08 UTC, guilhermehub12 approved these changes

2024-09-24 00:16 UTC, merged